### ISSUE TITLE
Error while installing drivers

### ISSUE THREAD

**Issue by Sunbownia** [WOA-Project/DriverUpdater#9] opened 2023-12-09 21:37 UTC
The program outputs
[Error] DriverStoreOfflineEousOriverPackage: ntStatus=0x80070003

Drivers are not being installed. Tried multiple versions of drivers, but none of them worked.

**Comment by gus33000** [comment] 2023-12-10 17:50
Hi, can you please provide a copy pasted line of the program output? This sounds incomplete and manually typed (typo presents) and misses important information (path should be provided).

Can you also provide the command line you use, as well as the driver package you're installing?

**Comment by system198** [comment] 2024-01-05 15:19
I managed to reproduce the issue on my end.
I use the install,esd from the Tiny11 arm build: https://archive.org/details/tiny11-core-arm64

Can be easily setup on a virtual drive for debuging instead of using an actual hardware (I am currently using Xiaomi Pad 5 - guide from https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/2-install-en.md ):

- Partition 1 as FAT32 'ESPNABU' - 512 MB Y:\
- Partition 2 as NTFS 'WINNABU' - _rest of the disk_ X:\

Driver files: https://github.com/map220v/MiPad5-Drivers/releases/latest

Manual Installation: 
`driverupdater.exe -d <nabudriversfolder>\definitions\Desktop\ARM64\Internal\nabu.txt -r <nabudriversfolder> -p X:`
ie. `driverupdater.exe -d D:\MiPad5-Drivers\definitions\Desktop\ARM64\Internal\nabu.txt -r D:\MiPad5-Drivers -p X:`


Log:
```
Microsoft Windows [Version 10.0.22621.2861]
(c) Microsoft Corporation. All rights reserved.

C:\Users\black>cd /d "D:\MiPad5-Drivers"

D:\MiPad5-Drivers>dism /apply-image /ImageFile:"D:\MiPad5-Drivers\install.esd" /index:1 /ApplyDir:X:\

Deployment Image Servicing and Management tool
Version: 10.0.22621.2792

Applying image
[==========================100.0%==========================]
The operation completed successfully.

D:\MiPad5-Drivers>driverupdater.exe -d D:\MiPad5-Drivers\definitions\Desktop\ARM64\Internal\nabu.txt -r D:\MiPad5-Drivers -p X:
[23:16:16][Information] DriverUpdater 2.0.0.0 - Cleans and Installs a new set of drivers onto a Windows Image
[23:16:16][Information] Copyright (c) 2017-2023, The LumiaWOA and DuoWOA Authors
[23:16:16][Information] https://github.com/WOA-Project/DriverUpdater

[23:16:16][Information] This program comes with ABSOLUTELY NO WARRANTY.
[23:16:16][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[23:16:16][Information] Reading definition file...
[23:16:17][Information] Enumerating existing drivers...
[23:16:17][   Error   ] DriverStoreOfflineEnumDriverPackage: ntStatus=0x80070003
[23:16:18][Information] Done!

D:\MiPad5-Drivers>
```

NTDEV theorizes that it is something to do with the _**Windows Component Store (WinSxS)**_ being remove on the Tiny11 Core build that I am currently using.

**Comment by system198** [comment] 2024-01-06 14:27
> Hi, can you please provide a copy pasted line of the program output? This sounds incomplete and manually typed (typo presents) and misses important information (path should be provided).
> 
> Can you also provide the command line you use, as well as the driver package you're installing?

I managed to reproduce the issue on my end.
I use the install,esd from the Tiny11 arm build: https://archive.org/details/tiny11-core-arm64

Can be easily setup on a virtual drive for debuging instead of using an actual hardware (I am currently using Xiaomi Pad 5 - guide from https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/blob/main/guide/English/2-install-en.md ):

- Partition 1 as FAT32 'ESPNABU' - 512 MB Y:\
- Partition 2 as NTFS 'WINNABU' - _rest of the disk_ X:\

Driver files: https://github.com/map220v/MiPad5-Drivers/releases/latest

Manual Installation: 
`driverupdater.exe -d <nabudriversfolder>\definitions\Desktop\ARM64\Internal\nabu.txt -r <nabudriversfolder> -p X:`
ie. `driverupdater.exe -d D:\MiPad5-Drivers\definitions\Desktop\ARM64\Internal\nabu.txt -r D:\MiPad5-Drivers -p X:`


Log:
```
Microsoft Windows [Version 10.0.22621.2861]
(c) Microsoft Corporation. All rights reserved.

C:\Users\black>cd /d "D:\MiPad5-Drivers"

D:\MiPad5-Drivers>dism /apply-image /ImageFile:"D:\MiPad5-Drivers\install.esd" /index:1 /ApplyDir:X:\

Deployment Image Servicing and Management tool
Version: 10.0.22621.2792

Applying image
[==========================100.0%==========================]
The operation completed successfully.

D:\MiPad5-Drivers>driverupdater.exe -d D:\MiPad5-Drivers\definitions\Desktop\ARM64\Internal\nabu.txt -r D:\MiPad5-Drivers -p X:
[23:16:16][Information] DriverUpdater 2.0.0.0 - Cleans and Installs a new set of drivers onto a Windows Image
[23:16:16][Information] Copyright (c) 2017-2023, The LumiaWOA and DuoWOA Authors
[23:16:16][Information] https://github.com/WOA-Project/DriverUpdater

[23:16:16][Information] This program comes with ABSOLUTELY NO WARRANTY.
[23:16:16][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[23:16:16][Information] Reading definition file...
[23:16:17][Information] Enumerating existing drivers...
[23:16:17][   Error   ] DriverStoreOfflineEnumDriverPackage: ntStatus=0x80070003
[23:16:18][Information] Done!

D:\MiPad5-Drivers>
```

NTDEV theorizes that it is something to do with the _**Windows Component Store (WinSxS)**_ being remove on the Tiny11 Core build.

This issue is not present when using an unmodified Windows 11 build - I got mine from uupdump.net

**Comment by bibarub** [comment] 2024-01-06 22:47
this doesn't happen on normal Windows images so it's not a bug ;)

**Comment by gus33000** [comment] 2024-01-06 23:16
Sorry. We do not support modified versions of windows nor devices we do not work on ourselves. Considering the problem is due to heavily modified versions of windows, I will close this issue as not planned. Use normal windows versions or work with the person doing the hacked together thing to fix their image. I will also rightfully point out drivers are never meant to work with such mods and realistically you are on your own at every step of the process here. Not to mention, there's only cons in using stripped down versions on hardware that doesn't need it at all.

**Closed as not planned** 2024-01-06 23:16 UTC
Labels: invalid
